version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network
    command: >
      sh -c "sleep 10 && python -m bot"

  postgres:
    image: postgres:15-alpine
    container_name: bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge